on:
  push:
    tags:
    - 'v*'

name: Bundle and Publish Sources
jobs:
  build:
    name: Bundle and Publish Sources
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: gulp bundle

      - name: Publish Artifacts
        uses: softprops/action-gh-release@v0.1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./bundles/source.MangaDex.js
            ./bundles/source.Manganelo.js
            ./bundles/source.MangaPark.js
            ./bundles/source.Mangasee.js
            ./bundles/versioning.json
