on:
  push:
    branches:
      - master
  pull_request:
      branches:
          - master

name: Bundle and Publish Sources
jobs:
  build:
    name: Bundle and Publish Sources
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: gulp bundle

      - name: Publish Artifacts to Bundle Directory
        uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
            commit_message: Sources Re-Bundle
            branch: ${{ github.head_ref }}
            file_pattern: bundles/*
